# name: First Workflow
# on: workflow_dispatch
# jobs: 
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hi
#         run: echo "Hi"
#       - name: Print Bye
#         run: echo "Done - Bye"
    
name: Nodejs Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./project
        run: npm install
      - name: Run tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./project
        run: npm install
      - name: Run deploy
        working-directory: ./project
        run: npm build