name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hi
        run: echo "Hi"
      - name: Print Bye
        run: echo "Done - Bye"
    
